---
- hosts: all
  tasks:
          #- name: Install GIT ppa
          #command: add-apt-repository ppa:git-core/ppa -y
          #become: yes
  
  - name: Update APT cache
    apt: 
      update_cache: yes
    become: yes
  
  - name: Install base packages
    apt:
      pkg: 
      #- git
      - binutils
    become: yes

  - name: Download Powershell deb
    get_url:
      url: "https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb"
      dest: /tmp/packages-microsoft-prod.deb
    
  - name: Install Powershell deb
    apt:
      deb: /tmp/packages-microsoft-prod.deb
    become: yes
  
  - name: Update APT cache
    apt: 
      update_cache: yes
    become: yes
  
  - name: Install Powershell packages
    apt:
      name: powershell
    become: yes

  - name: Remove Docker GPG key if it exists
    file:
      path: /usr/share/keyrings/docker-archive-keyring.gpg
      state: absent
    become: yes


  - name: Add Docker GPG key
    shell: >
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    become: yes
  
  - name: Set permissions on Docker GPG key
    file:
      path: /usr/share/keyrings/docker-archive-keyring.gpg
      mode: a+rw
    become: yes

  - name: Install Docker repository
    shell: >
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    become: yes

  - name: Update APT cache
    apt: 
      update_cache: yes
    become: yes

  - name: Install Docker packages
    apt:
      pkg: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
    become: yes
