---
- hosts: all
  tasks:
  - name: Install GIT ppa
    command: add-apt-repository ppa:git-core/ppa -y
    become: yes
  
  - name: Update APT cache
    apt: 
      update_cache: yes
    become: yes
  
  - name: Install base packages
    apt:
      pkg: 
      - git
    become: yes