---
- hosts: all
  tasks:
    - name: Download miniconda
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/miniconda.sh
    
    - name: Set permissions on miniconda script
      file:
        path: /tmp/miniconda.sh
        mode: a+x

    - name: Install miniconda
      command: /tmp/miniconda.sh -b -p $HOME/miniconda

    - name: Initialize miniconda
      command: $HOME/miniconda/bin/conda init 